# Generated by CoffeeScript 1.7.1
define [
  "jquery"
  "underscore"
  "backbone"
  "views/header"
  "views/content"
  "models/task"
], ($, _, Backbone, HeaderView, ContentView, TaskModel) ->

	AppRouter = Backbone.Router.extend(routes:
		"": "index"
		"*actions": "defaultAction"
	)

	initialize = ->
    router = new AppRouter()
    @headerView = new HeaderView()
    @contentView = new ContentView()
    @layoutViews()

    router.on "route:optimize", ->
      require ["views/optimize/page"], (OptimizePage) ->
        optimizePage = Vm.create(appView, "OptimizePage", OptimizePage)
        optimizePage.render()
        return
      return

    router.on "route:index", =>
      require ["views/new_task", "views/tasks", "collections/tasks"], (NewTaskView, TasksView, TasksCollection) =>
        @contentView.swapSide(new NewTaskView({ model: new TaskModel }))
        @contentView.swapMain(new TasksView({ collection: new TasksCollection }))

    router.on "route:defaultAction", (actions) ->
      console.log "There is no action for: - " + actions
      return

    Backbone.history.start()
    return

  layoutViews: ->
    $("#header").html @headerView.render().el
    $("#content").html @contentView.render().el

  initialize: initialize
