# Generated by CoffeeScript 1.7.1
define [
  "jquery"
  "underscore"
  "backbone"
  "views/header"
  "views/content"
], ($, _, Backbone, Header, Content) ->

	AppRouter = Backbone.Router.extend(routes:
		"": "index"
		"*actions": "defaultAction"
	)

	initialize = ->
    router = new AppRouter()
    @headerView = new Header()
    @contentView = new Content()
    @layoutViews()

    router.on "route:optimize", ->
      require ["views/optimize/page"], (OptimizePage) ->
        optimizePage = Vm.create(appView, "OptimizePage", OptimizePage)
        optimizePage.render()
        return
      return

    router.on "route:index", =>
      require ["views/new_task"], (NewTask) =>
        @contentView.swapSide(new NewTask())

    router.on "route:defaultAction", (actions) ->
      console.log "There is no action for: - " + actions
      return

    Backbone.history.start()
    return

  layoutViews: ->
    $("#header").html @headerView.render().el
    $("#content").html @contentView.render().el

  initialize: initialize
