// Generated by CoffeeScript 1.7.1
(function() {
  define(['backbone'], function(Backbone) {
    return describe('A Task', function() {
      return it('backbone should be defined', function() {
        return expect(Backbone).toBeDefined();
      });
    });
  });

}).call(this);
