// Generated by CoffeeScript 1.7.1
(function() {
  define(['sinon', 'public/javascripts/backbone/models/todo', 'public/javascripts/vendor/sinon/jasmine-sinon'], function(Sinon, Todo, jsinon) {
    describe('check require is including files', function() {
      it('should include sinon', function() {
        return expect(Sinon).toBeDefined();
      });
      return it('should include Todo', function() {
        return expect(Todo).toBeDefined();
      });
    });
    return describe('testem model', function() {
      return describe('when instantiated', function() {
        beforeEach(function() {
          return this.todo = new Todo({
            title: "Rake leaves"
          });
        });
        it('should exhibit attributes', function() {
          return expect(this.todo.get('title')).toEqual('Rake leaves');
        });
        it('should set the priority to default', function() {
          return expect(this.todo.get('priority')).toEqual(3);
        });
        it('should set the url to the collection URL', function() {
          var collection;
          collection = {
            url: '/collection'
          };
          this.todo.collection = collection;
          return expect(this.todo.url()).toEqual('/collection');
        });
        return describe('url', function() {
          beforeEach(function() {
            var collection;
            collection = {
              url: '/collection'
            };
            return this.todo.collection = collection;
          });
          describe('when no id is set', function() {
            return it('should return the collection url', function() {
              return expect(this.todo.url()).toEqual('/collection');
            });
          });
          return describe('when id is set', function() {
            return it('should return the collection url and id', function() {
              this.todo.id = 1;
              return expect(this.todo.url()).toEqual('/collection/1');
            });
          });
        });
      });
    });
  });

}).call(this);
